FROM apache/airflow:3.1.0-python3.13

COPY requirements.txt /requirements.txt

# COPY jobs /opt/jobs

COPY .env /opt/airflow/.env

USER airflow
RUN pip install --no-cache-dir -r /requirements.txt

USER root
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

USER airflow