SEQUENCE_LEGHTH = 24

FEATURE_COLS_LSTM_SOLAR = [
    "shortwave_radiation",
    "direct_radiation",
    "diffuse_radiation",
    "direct_normal_irradiance",
    "cloudcover",
    "cloudcover_low",
    "cloudcover_mid",
    "cloudcover_high",
    "temperature_2m",
    "relativehumidity_2m",
    "solar_count",
    "dewpoint_2m",
    "surface_pressure",
    "time",
    "rain",
    "season",
    "day",
    "month",
    "is_night",
    "sin_time",
    "cos_time",
    "day_of_month_sin",
    "day_of_month_cos",
    "month_of_year_sin",
    "month_of_year_cos",
]

FEATURE_COLS_LSTM_WIND = [
    "windspeed_10m",
    "winddirection_10m",
    "windspeed_100m",
    "winddirection_100m",
    "windgusts_10m",
    "temperature_2m",
    "dewpoint_2m",
    "relativehumidity_2m",
    "surface_pressure",
    "cloudcover",
    "cloudcover_low",
    "cloudcover_mid",
    "cloudcover_high",
    "sin_doy",
    "cos_doy",
    "sin_time",
    "cos_time",
    "wind_turbine_count"
]